# Generated by Django 4.2.3 on 2025-09-17 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triviagroup',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triviagroup',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_groups', to='home.church'),
        ),
        migrations.AddField(
            model_name='triviagroup',
            name='members',
            field=models.ManyToManyField(related_name='trivia_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triviagroup',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patroned_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['slug'], name='home_questi_slug_5b2106_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['is_active'], name='home_questi_is_acti_3c59eb_idx'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.questioncategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='churchcategory',
            index=models.Index(fields=['slug'], name='home_church_slug_134a1a_idx'),
        ),
        migrations.AddField(
            model_name='church',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='churches', to='home.churchcategory'),
        ),
        migrations.AddField(
            model_name='church',
            name='manager',
            field=models.ForeignKey(help_text='User who manages/created this church', on_delete=django.db.models.deletion.CASCADE, related_name='managed_churches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.question'),
        ),
        migrations.AddIndex(
            model_name='triviagroup',
            index=models.Index(fields=['slug'], name='home_trivia_slug_ed2573_idx'),
        ),
        migrations.AddIndex(
            model_name='triviagroup',
            index=models.Index(fields=['church', 'is_active'], name='home_trivia_church__582355_idx'),
        ),
        migrations.AddIndex(
            model_name='triviagroup',
            index=models.Index(fields=['category'], name='home_trivia_categor_c74252_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='triviagroup',
            unique_together={('church', 'name')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'difficulty'], name='home_questi_categor_b187b3_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='home_questi_is_acti_b6e2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by'], name='home_questi_created_bc0736_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['slug'], name='home_church_slug_7cac42_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['is_active'], name='home_church_is_acti_973fa4_idx'),
        ),
    ]
