# Generated by Django 4.2.3 on 2025-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='home_questi_categor_b187b3_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='questions', to='home.questioncategory'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(choices=[('Old Testament', 'Old Testament'), ('New Testament', 'New Testament'), ('Church History', 'Church History'), ('General Knowledge', 'General Knowledge'), ('Other', 'Other')], max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='home_questi_difficu_777d4a_idx'),
        ),
    ]
