# Generated by Django 4.2.13 on 2025-09-17 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_activitycategory_cohort_competition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the quiz')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('quiz_type', models.CharField(choices=[('Practice', 'Practice'), ('Assessment', 'Assessment'), ('Competition', 'Competition'), ('Study', 'Study')], default='Practice', max_length=20)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (null = no limit)', null=True)),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum score percentage to pass')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total possible points for this quiz')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Available to all users')),
                ('requires_authentication', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions for taking this quiz')),
                ('metadata', models.JSONField(blank=True, help_text='Additional quiz settings and data', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_test_quizzes', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, help_text='Questions included in this quiz', related_name='test_quizzes', to='home.question')),
            ],
            options={
                'verbose_name': 'Test Quiz',
                'verbose_name_plural': 'Test Quizzes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='home_testqu_slug_aff155_idx'), models.Index(fields=['is_active'], name='home_testqu_is_acti_6b7578_idx'), models.Index(fields=['quiz_type'], name='home_testqu_quiz_ty_70ea20_idx'), models.Index(fields=['difficulty'], name='home_testqu_difficu_3f755b_idx'), models.Index(fields=['created_by'], name='home_testqu_created_498738_idx')],
            },
        ),
    ]
