# Generated by Django 4.2.13 on 2025-09-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquiz',
            name='level',
            field=models.CharField(choices=[('Adults', 'Adults'), ('Youth', 'Youth'), ('Children', 'Children'), ('Senior', 'Senior'), ('Junior', 'Junior'), ('Teens', 'Teens'), ('All', 'All')], default='All', max_length=100),
        ),
    ]
