# Generated by Django 4.2.13 on 2025-09-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_question_question_type_testquiz_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='penalty',
            field=models.PositiveIntegerField(default=1, help_text='If 0, allow positive proportional credit for multiple-select; otherwise full-or-nothing'),
        ),
    ]
