# Generated by Django 4.2.13 on 2025-09-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userranking_groupranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionactivity',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='home.activitycategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(choices=[('Pictorial', 'Pictorial'), ('Pointless', 'Pointless'), ('Bible Sprint', 'Bible Sprint'), ('Speed', 'Speed')], max_length=100),
        ),
    ]
