# Generated by Django 4.2.13 on 2025-09-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_competitionactivity_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionactivity',
            name='category',
        ),
        migrations.AddField(
            model_name='competitionactivity',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='activities', to='home.activitycategory'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(choices=[('Online', 'Online'), ('Stage', 'Stage')], max_length=100),
        ),
        migrations.CreateModel(
            name='ActivityInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='home.competitionactivity')),
            ],
            options={
                'verbose_name': 'Activity Instruction',
                'verbose_name_plural': 'Activity Instructions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='home.competitionactivity')),
            ],
            options={
                'verbose_name': 'Activity Rule',
                'verbose_name_plural': 'Activity Rules',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['activity', 'order'], name='home_activi_activit_31c17c_idx'), models.Index(fields=['is_active'], name='home_activi_is_acti_812943_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='activityrule',
            constraint=models.UniqueConstraint(fields=('activity', 'order'), name='uniq_rule_activity_order'),
        ),
        migrations.AddIndex(
            model_name='activityinstruction',
            index=models.Index(fields=['activity', 'order'], name='home_activi_activit_2ff8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='activityinstruction',
            index=models.Index(fields=['is_active'], name='home_activi_is_acti_781bc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityinstruction',
            constraint=models.UniqueConstraint(fields=('activity', 'order'), name='uniq_instruction_activity_order'),
        ),
    ]
