# Generated by Django 4.2.13 on 2025-09-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_competitionactivity_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video File'), ('embed', 'External URL/Embed')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='competition_media/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='competition_media/videos/')),
                ('url', models.URLField(blank=True, help_text='External media URL (e.g., YouTube)', null=True)),
                ('intro_media', models.BooleanField(default=False, help_text='Show before activities (max 1 per competition)')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='home.competition')),
            ],
            options={
                'verbose_name': 'Competition Media',
                'verbose_name_plural': 'Competition Media',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['competition', 'order'], name='home_compet_competi_6f4cea_idx'), models.Index(fields=['is_active'], name='home_compet_is_acti_f54bd1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='competitionmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('intro_media', True)), fields=('competition',), name='uniq_intro_media_per_competition'),
        ),
    ]
