# Generated by Django 4.2.13 on 2025-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_competitionvenue_competitionsponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionbooking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='competitionbooking',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='competitionbooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('paypal_card', 'PayPal/Card'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='competitionbooking',
            name='payment_receipt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='competitionbooking',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='activities',
            field=models.ManyToManyField(blank=True, help_text='Activities this question is associated with', related_name='questions', to='home.competitionactivity'),
        ),
    ]
