# Generated by Django 4.2.13 on 2025-09-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_competitionbooking_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquiz',
            name='activities',
            field=models.ManyToManyField(blank=True, help_text='Activities this quiz is associated with', related_name='quizzes', to='home.competitionactivity'),
        ),
    ]
