# Generated by Django 4.2.13 on 2025-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_testquiz_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allowed_levels',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more levels this question applies to'),
        ),
    ]
