# Generated by Django 4.2.13 on 2025-09-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_challenge_challengeparticipant_challengeround_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='max_participants',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of participants allowed in this challenge'),
        ),
    ]
